services:

  elastic:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    networks:
      - prod_server

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    networks:
      - prod_server

#  logstash:
#    image: docker.elastic.co/logstash/logstash:8.12.0
#    container_name: logstash

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - prod_server 
    restart: unless-stopped

networks:
  prod_server:
    external: true




